### ISSUE TITLE
[Resolved]Unkonwn reference issue when running the script

### ISSUE THREAD

**Issue by Labibme** [WtfJoke/rtc2git#114]
Hello, 

### I tried to run the python project for migration, but i got everytime same messages as described below:

+refs/heads/TEST-RTC
 +refs/heads/TEST-RTC_branchpoint
 +Configured directory already exists, please make sure to use a non-existing directory

### lscm and git command working correctly without any issue, example:
$lscm --show-alias n --show-uuid y show attributes -r http://*****************
RITMx_TMA_DEV_RC66-2
(_j4idAKU6EeaPqMc7O-9shg) "RITMx_TMA_DEV_RC66-2"
  Référentiel : http://**********************

### Debug mode:

> /home/ritmx-group/sboukari/rtc2git/rtc2git/migration.py(3)<module>()
-> import os
(Pdb) n
> /home/ritmx-group/sboukari/rtc2git/rtc2git/migration.py(4)<module>()
-> import sys
(Pdb) n
> /home/ritmx-group/sboukari/rtc2git/rtc2git/migration.py(5)<module>()
-> import argparse
(Pdb) n
> /home/ritmx-group/sboukari/rtc2git/rtc2git/migration.py(7)<module>()
-> from rtcFunctions import ImportHandler
(Pdb) n
> /home/ritmx-group/sboukari/rtc2git/rtc2git/migration.py(8)<module>()
-> from rtcFunctions import WorkspaceHandler
(Pdb) n
> /home/ritmx-group/sboukari/rtc2git/rtc2git/migration.py(9)<module>()
-> from rtcFunctions import RTCInitializer
(Pdb) n
> /home/ritmx-group/sboukari/rtc2git/rtc2git/migration.py(10)<module>()
-> from rtcFunctions import RTCLogin
(Pdb) n
> /home/ritmx-group/sboukari/rtc2git/rtc2git/migration.py(11)<module>()
-> from gitFunctions import Initializer, Differ
(Pdb) n
> /home/ritmx-group/sboukari/rtc2git/rtc2git/migration.py(12)<module>()
-> from gitFunctions import Commiter
(Pdb) n
> /home/ritmx-group/sboukari/rtc2git/rtc2git/migration.py(13)<module>()
-> import configuration
(Pdb) n
> /home/ritmx-group/sboukari/rtc2git/rtc2git/migration.py(14)<module>()
-> import shouter
(Pdb) n
> /home/ritmx-group/sboukari/rtc2git/rtc2git/migration.py(17)<module>()
-> def initialize():
(Pdb) n
> /home/ritmx-group/sboukari/rtc2git/rtc2git/migration.py(34)<module>()
-> def resume():
(Pdb) s
> /home/ritmx-group/sboukari/rtc2git/rtc2git/migration.py(49)<module>()
-> def existsrepo():
(Pdb) s
> /home/ritmx-group/sboukari/rtc2git/rtc2git/migration.py(55)<module>()
-> def migrate():
(Pdb) s
> /home/ritmx-group/sboukari/rtc2git/rtc2git/migration.py(96)<module>()
-> def prepare():
(Pdb) s
> /home/ritmx-group/sboukari/rtc2git/rtc2git/migration.py(109)<module>()
-> def summary(streamname):
(Pdb) s
> /home/ritmx-group/sboukari/rtc2git/rtc2git/migration.py(136)<module>()
-> def parsecommandline():
(Pdb) s
> /home/ritmx-group/sboukari/rtc2git/rtc2git/migration.py(150)<module>()
-> def validate():
(Pdb) s
> /home/ritmx-group/sboukari/rtc2git/rtc2git/migration.py(166)<module>()
-> if __name__ == "__main__":
(Pdb) s
> /home/ritmx-group/sboukari/rtc2git/rtc2git/migration.py(167)<module>()
-> parsecommandline()
(Pdb) s
--Call--
> /home/ritmx-group/sboukari/rtc2git/rtc2git/migration.py(136)parsecommandline()
-> def parsecommandline():
(Pdb) s
> /home/ritmx-group/sboukari/rtc2git/rtc2git/migration.py(137)parsecommandline()
-> parser = argparse.ArgumentParser()
(Pdb) s
--Call--
> /products/python3.4/lib/python3.4/argparse.py(1600)__init__()
-> def __init__(self,
(Pdb) s
> /products/python3.4/lib/python3.4/argparse.py(1613)__init__()
-> superinit = super(ArgumentParser, self).__init__
(Pdb) s
> /products/python3.4/lib/python3.4/argparse.py(1614)__init__()
-> superinit(description=description,
(Pdb) s
> /products/python3.4/lib/python3.4/argparse.py(1615)__init__()
-> prefix_chars=prefix_chars,
(Pdb) s
> /products/python3.4/lib/python3.4/argparse.py(1616)__init__()
-> argument_default=argument_default,
(Pdb) s
> /products/python3.4/lib/python3.4/argparse.py(1617)__init__()
-> conflict_handler=conflict_handler)
(Pdb) n
> /products/python3.4/lib/python3.4/argparse.py(1620)__init__()
-> if prog is None:
(Pdb) n
> /products/python3.4/lib/python3.4/argparse.py(1621)__init__()
-> prog = _os.path.basename(_sys.argv[0])
(Pdb) n
> /products/python3.4/lib/python3.4/argparse.py(1623)__init__()
-> self.prog = prog
(Pdb) n
> /products/python3.4/lib/python3.4/argparse.py(1624)__init__()
-> self.usage = usage
(Pdb) n
> /products/python3.4/lib/python3.4/argparse.py(1625)__init__()
-> self.epilog = epilog
(Pdb) n
> /products/python3.4/lib/python3.4/argparse.py(1626)__init__()
-> self.formatter_class = formatter_class
(Pdb) n
> /products/python3.4/lib/python3.4/argparse.py(1627)__init__()
-> self.fromfile_prefix_chars = fromfile_prefix_chars
(Pdb) n
> /products/python3.4/lib/python3.4/argparse.py(1628)__init__()
-> self.add_help = add_help
(Pdb) n
> /products/python3.4/lib/python3.4/argparse.py(1630)__init__()
-> add_group = self.add_argument_group
(Pdb) n
> /products/python3.4/lib/python3.4/argparse.py(1631)__init__()
-> self._positionals = add_group(_('positional arguments'))
(Pdb) n
> /products/python3.4/lib/python3.4/argparse.py(1632)__init__()
-> self._optionals = add_group(_('optional arguments'))
(Pdb) n
> /products/python3.4/lib/python3.4/argparse.py(1633)__init__()
-> self._subparsers = None
(Pdb) n
> /products/python3.4/lib/python3.4/argparse.py(1636)__init__()
-> def identity(string):
(Pdb) n
> /products/python3.4/lib/python3.4/argparse.py(1638)__init__()
-> self.register('type', None, identity)
(Pdb) n
> /products/python3.4/lib/python3.4/argparse.py(1642)__init__()
-> default_prefix = '-' if '-' in prefix_chars else prefix_chars[0]
(Pdb) n
> /products/python3.4/lib/python3.4/argparse.py(1643)__init__()
-> if self.add_help:
(Pdb) n
> /products/python3.4/lib/python3.4/argparse.py(1644)__init__()
-> self.add_argument(
(Pdb) n
> /products/python3.4/lib/python3.4/argparse.py(1645)__init__()
-> default_prefix+'h', default_prefix*2+'help',
(Pdb) n
> /products/python3.4/lib/python3.4/argparse.py(1646)__init__()
-> action='help', default=SUPPRESS,
(Pdb) n
> /products/python3.4/lib/python3.4/argparse.py(1647)__init__()
-> help=_('show this help message and exit'))
(Pdb) n
> /products/python3.4/lib/python3.4/argparse.py(1650)__init__()
-> for parent in parents:
(Pdb) n
--Return--
> /products/python3.4/lib/python3.4/argparse.py(1650)__init__()->None
-> for parent in parents:
(Pdb) n
> /home/ritmx-group/sboukari/rtc2git/rtc2git/migration.py(138)parsecommandline()
-> configfiledefault = 'config.ini'
(Pdb) n
> /home/ritmx-group/sboukari/rtc2git/rtc2git/migration.py(139)parsecommandline()
-> configfilehelp = 'name of the config file, or full path to the config file; defaults to ' + configfiledefault
(Pdb) n
> /home/ritmx-group/sboukari/rtc2git/rtc2git/migration.py(140)parsecommandline()
-> parser.add_argument('-c', '--configfile', metavar='file', dest='configfile', help=configfilehelp,
(Pdb) n
> /home/ritmx-group/sboukari/rtc2git/rtc2git/migration.py(141)parsecommandline()
-> default=configfiledefault)
(Pdb) n
> /home/ritmx-group/sboukari/rtc2git/rtc2git/migration.py(142)parsecommandline()
-> parser.add_argument('-u', '--user', metavar='user', dest='user', help='RTC user', default=None)
(Pdb) n
> /home/ritmx-group/sboukari/rtc2git/rtc2git/migration.py(143)parsecommandline()
-> parser.add_argument('-p', '--password', metavar='password', dest='password', help='RTC password', default=None)
(Pdb) n
> /home/ritmx-group/sboukari/rtc2git/rtc2git/migration.py(144)parsecommandline()
-> arguments = parser.parse_args()
(Pdb) n
> /home/ritmx-group/sboukari/rtc2git/rtc2git/migration.py(145)parsecommandline()
-> configuration.setconfigfile(arguments.configfile)
(Pdb) n
> /home/ritmx-group/sboukari/rtc2git/rtc2git/migration.py(146)parsecommandline()
-> configuration.setUser(arguments.user)
(Pdb) n
> /home/ritmx-group/sboukari/rtc2git/rtc2git/migration.py(147)parsecommandline()
-> configuration.setPassword(arguments.password)
(Pdb) n
--Return--
> /home/ritmx-group/sboukari/rtc2git/rtc2git/migration.py(147)parsecommandline()->None
-> configuration.setPassword(arguments.password)
(Pdb) n
> /home/ritmx-group/sboukari/rtc2git/rtc2git/migration.py(168)<module>()
-> validate()
(Pdb) n
refs/heads/RITMx_TMA_DEV_RC66-2
refs/heads/RITMx_TMA_DEV_RC66-2_branchpoint
> /home/ritmx-group/sboukari/rtc2git/rtc2git/migration.py(169)<module>()
-> migrate()

thanks,

**Comment by Labibme** [comment]
Hi, 

## Script work only when i comment those lines:

$sudo vim /products/python3.4/lib/python3.4/os.py +238
def makedirs(name, mode=0o777, exist_ok=False): // i changed exist_ok==> True

## and on "migration.py":
$vim migration.py  +20
if os.path.exists(directory):
sys.exit("Configured directory already exists, please make sure to use a non-existing directory")

Any ideas?

**Comment by WtfJoke** [comment]
Hi Labibme

Which message do you got?
This one? `Configured directory already exists, please make sure to use a non-existing directory`

And you dont have referenced, a directory which is already there? This error pops up, when the folder where the migration takes place already exists and is not created by the script.

**Comment by Labibme** [comment]
Hi @WtfJoke,

Yes, i understand exactly what you explained. But i didn't reference any existing files and i tried every time to remove downloaded files ( clean git cache, init, etc..), error didn't disappear.

Solution was to modify the ### python/os.py files. 
Now i can download, and i notice that we can't run the script more than one time for same workspace/stream ( i dont know why). 
Also, files are only downloaded locally but the programe ( rtc2git) is uploaded to configured directory with given "streamName".

More thing, i would like to know if there's another references for "Howto".
For example, if i want to migrate many stream, where i can find a guide for such case.

Many thanks @WtfJoke !

**Comment by WtfJoke** [comment]
When you start migration, your config should reference to a folder which doesnt exist yet. 
For example you want to migrate in a folder migration inside your home (folder migration is **not** created):
You write in your config:
```
# Folder to be created - where migration will take place
Directory = /home/ritmx-group/sboukari/migration
```

Then two folders inside there will be created myGitRepo and myGitRepo.git.

Does the above scenario work for you? Currently im not sure if I understand your problem correcly. >.<

Note: myGitRepo.git you can upload as bare repository to any git server, after migration is finished.






> More thing, i would like to know if there's another references for "Howto".
> For example, if i want to migrate many stream, where i can find a guide for such case.

There's no other reference for Howto...

To answer your question:
If you want to migrate multiple streams to one git repo, you can do the following steps:

1. Finish Migration of 1 Stream.
2. Change StreamToMigrate to the next stream, change WorkspaceName to a different one
3. Rerun the script --> It should find the existing git repo and continue.

**Comment by Labibme** [comment]
Hi, 
Yeah, your explanation's perfect for me. But, i don't know why "makedirs" function is not good for me.
Actually, with "True" value it work correctly as you explained below. 
Thanks a lot for help!

**Comment by WtfJoke** [comment]
ok strange, but glad I was able to help you :)
