### ISSUE TITLE
getRTCHistory 

### ISSUE THREAD

**Issue by Vad1mo** [WtfJoke/rtc2git#115]
this is not an issue, I just wanted to let you know that the command line tool getRTCHistory is working as expected. I can see component history with +10000 entries

We are using RTC 6.0.2

**Comment by WtfJoke** [comment]
Thanks for the feedback

**Comment by buster3** [comment]
As a hint for anybody struggling with RTC history files. From me non of the suggested solutions on https://github.com/rtcTo/rtc2git/wiki/Getting-your-History-Files worked.

- The eclipse client crashed or timed out for a large number of changesets.
- The getRTCHistory.sh script produced incorrectly ordered changesets

Finally, I succeeded querying history form the web client. (Inspiration https://fschop.wordpress.com/2020/02/29/rtc2git-rational-team-concert-to-git-migration-part-1/)

https://gist.github.com/buster3/be2541cb32dfc48e863f2ffa8155e685
