### ISSUE TITLE
Unable to execute migration script

### ISSUE THREAD

**Issue by muthukumarc17** [WtfJoke/rtc2git#118]
If I execute the migration.py script, I am getting the below error:

D:\tools\rtc2git-develop\rtc2git-develop>python migration.py
Traceback (most recent call last):
  File "migration.py", line 7, in <module>
    from rtcFunctions import ImportHandler
  File "D:\tools\rtc2git-develop\rtc2git-develop\rtcFunctions.py", line 4, in <module>
    from enum import Enum, unique
ImportError: No module named enum

Could you please tell me if this script is still under development ? OR is there something wrong in executing the script from my end ?

My config.ini file looks like below : (I have masked my pwd here)

[General]
Repo=https://jazz.net/sandbox01-ccm
User=muthukumarc17
Password=**************
GIT-Reponame = myGitRepo.git
WorkspaceName=GitWork

[Migration]
# Stream to be migrated, referenced by Name or UUID
StreamToMigrate = Streamm1

Would be great if you comment on this ASAP ? Thanks !

**Comment by ohumbel** [comment]
What version of Python do you use?

`python --version`

The README says the minimum required version is `3.4`
I suspect you are using a `2.x` or a pre `3.4` version.

**Comment by muthukumarc17** [comment]
Hi, initially I tried with 3.6 version as its mentioned in the README. But with 3.6 version, the script was not working. So, then i tried with 3.3.5 and 2.7.13 versions also. But still I am getting the same error.

**Comment by WtfJoke** [comment]
[Enums are supported since 3.4](https://docs.python.org/3.6/library/enum.html).
With 3.6 it would be strange if you run into the same error. Can you attach the 3.6 error? Or test with 3.5?

**Comment by muthukumarc17** [comment]
Thanks all. With 3.5 version of python, it works fine. But I am struck with some JAVA issue as of now, I am also looking into it. Would be great if you have experienced already the below errors:

Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Unrecognized option: -Xshareclasses:nonfatal
Scm:
Java was started but returned exit code=1
C:\Windows\system32\java.exe
-Xmx512m
-Xshareclasses:nonfatal
-Xquickstart

I am running this script on Windows machine. Hope the script supports both Unix and windows.

**Comment by WtfJoke** [comment]
It does support unix and windows.
Consult the [wiki](https://github.com/rtcTo/rtc2git/wiki/configure-RTC-CLI) how to setup java vm

**Comment by WtfJoke** [comment]
I'll close this. If you need further support, feel free to reopen this issue
