### ISSUE TITLE
Invalid Syntax error

### ISSUE THREAD

**Issue by ljhaywar** [WtfJoke/rtc2git#12]
When I run migration.py, I'm getting a SyntaxError.
![syntax](https://cloud.githubusercontent.com/assets/3940962/7515188/c9611836-f492-11e4-8aa2-fa6fe502b319.PNG)

I'm running Python 2.7.6 on Windows.  Any ideas on how to fix this?

**Comment by WtfJoke** [comment]
Hi Lihaywar,

You need Python 3+ in order to run the programm. Then it should work :)

**Comment by ljhaywar** [comment]
Thanks for the fast response! Updating to Python 3.4 fixed that issue.
