### ISSUE TITLE
Parser component and baseline (codes and names) in any languages

### ISSUE THREAD

**Issue by lmcarreiro** [WtfJoke/rtc2git#122]
Using the script in a RTC repository that use another language (in this case, portuguese/brazil) doesn't work, because of the `.split(<index>)` strategy of parsing these information. In portuguese, the word "baseline" (1 word) is translated to "Linha de base" (3 words).

Maybe if it will be done using regex, it will work in any language...

```
Área de trabalho: (_N7gfkOpHEea2mZ_Dzsl1FA) "<stream name>"
  Componente: (_OFC2EOpHEea2mZ_Dzsl1FA) "<component name>"
    Linha de base: (_OFOcRepHEea2mZ_Dzsl1FA) 1 "<baseline name>"
  Componente: (_OCrekOpHEea2mZ_Dzsl1FA) "<component name>"
    Linha de base: (_OC4S6epHEea2mZ_Dzsl1FA) 1 "<baseline name>"
  Componente: (_N88C8OpHEea2mZ_Dzsl1FA) "<component name>"
    Linha de base: (_N9NIs-pHEea2mZ_Dzsl1FA) 1 "<baseline name>"
```

**Comment by WtfJoke** [comment]
Hi Lmcarreiro

Did you set the language of scm to english like described [here- Set language to English](https://github.com/rtcTo/rtc2git/wiki/configure-RTC-CLI#set-language-to-english)?

**Comment by lmcarreiro** [comment]
I wasn't... sorry!

Closing this issue.
