### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by digitalLumberjack** [WtfJoke/rtc2git#123]
Hi, thank for this project. I want to save companies from RTC and Jazz with this project.

A docker support could be interesting.

We could use a simple docker run to perform a migration.

**Comment by WtfJoke** [comment]
Hi DigitalLumberJack

Actually a teammate did already setup a docker image, its also on dockerhub.
You can find it here:
https://github.com/rtcTo/rtc2git-docker/tree/master

Branch master is this project (dont know if the code base is up to date, though) and branch java-plugin represents rtc2gitcli.

**Comment by reinhapa** [comment]
@digitalLumberjack there are already some docker images on docker hub:
[https://hub.docker.com/r/rtcto/rtc2git/](https://hub.docker.com/r/rtcto/rtc2git/)
