### ISSUE TITLE
This migrate the repository history?

### ISSUE THREAD

**Issue by julioarruda** [WtfJoke/rtc2git#124]
Guys, this tool migrate the repository history too? i'ld like to migrate repository and history, but in my tests only the code goes to git..

**Comment by reinhapa** [comment]
@julioarruda yes it does, it was the purpose to have the history migrated.

**Comment by julioarruda** [comment]
How I do this? I don't see this in the Wiki...

**Comment by julioarruda** [comment]
In my Test, I used the Docker version... The repository Git generate have only one commit.. "Initial Commit Rtc2Git"

**Comment by reinhapa** [comment]
@julioarruda I created a initial [Wiki](https://github.com/rtcTo/rtc2git-docker/wiki) on rtc2git-docker that may help making your first steps.

**Comment by WtfJoke** [comment]
Can you provide your log?

Usually, the tool tries to setup a new workspace with the oldest baseline and accept one rtc changeset after each other.

Seems like it cant determine your oldest baseline (or there arent any) if you have just one commit.

In this case you need to setup yourself a workspace, which should have the oldest possible state(e.g your first rtc commit). And set useexistingworkspace=true in config

**Comment by julioarruda** [comment]
@WtfJoke this is the log


!SESSION 2017-07-31 00:35:13.818 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_111
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en
Framework arguments:  migrate-to-git -r <link> -u <user> -P <pwd> <repo> <repo>
Command-line arguments:  -os linux -ws gtk -arch x86_64 -data @noDefault migrate-to-git -r <link> -u <user> -P <pwd> <repo> <repo>


!ENTRY org.eclipse.osgi 2 1 2017-07-31 00:35:15.408
!MESSAGE NLS missing message: StringUtil_0 in: com.ibm.team.rtc.cli.infrastructure.internal.messages

!ENTRY org.eclipse.osgi 2 1 2017-07-31 00:35:15.415
!MESSAGE NLS missing message: StringUtil_1 in: com.ibm.team.rtc.cli.infrastructure.internal.messages

!ENTRY org.eclipse.osgi 2 1 2017-07-31 00:35:15.837
!MESSAGE NLS unused message: Application_0 in: com.ibm.team.filesystem.cli.core.internal.messages

!ENTRY org.eclipse.osgi 2 1 2017-07-31 00:35:15.837
!MESSAGE NLS unused message: Application_INVALID_SELECTOR in: com.ibm.team.filesystem.cli.core.internal.messages

!ENTRY org.eclipse.osgi 2 1 2017-07-31 00:35:15.837
!MESSAGE NLS unused message: SubcommandDefinition_11 in: com.ibm.team.filesystem.cli.core.internal.messages

!ENTRY org.eclipse.osgi 2 1 2017-07-31 00:35:15.837
!MESSAGE NLS unused message: SubcommandDefinition_12 in: com.ibm.team.filesystem.cli.core.internal.messages

!ENTRY org.eclipse.osgi 2 1 2017-07-31 00:35:15.838
!MESSAGE NLS unused message: SubcommandDefinition_13 in: com.ibm.team.filesystem.cli.core.internal.messages

!ENTRY org.eclipse.osgi 2 1 2017-07-31 00:35:15.839
!MESSAGE NLS unused message: RepoUtil_CANNOT_DETERMINE_REPO_URI_explanation in: com.ibm.team.filesystem.cli.core.internal.messages

!ENTRY org.eclipse.osgi 2 1 2017-07-31 00:35:15.839
!MESSAGE NLS unused message: RepoUtil_CANNOT_DETERMINE_REPO_URI_useraction in: com.ibm.team.filesystem.cli.core.internal.messages

!ENTRY org.eclipse.osgi 2 1 2017-07-31 00:35:15.839
!MESSAGE NLS unused message: StringUtil_0 in: com.ibm.team.filesystem.cli.core.internal.messages

!ENTRY org.eclipse.osgi 2 1 2017-07-31 00:35:15.839
!MESSAGE NLS unused message: StringUtil_1 in: com.ibm.team.filesystem.cli.core.internal.messages

!ENTRY org.eclipse.osgi 2 1 2017-07-31 00:35:15.841
!MESSAGE NLS missing message: PositionalOptionDefinition_0 in: com.ibm.team.filesystem.cli.core.internal.messages

**Comment by julioarruda** [comment]
The git log...
![image](https://user-images.githubusercontent.com/5204009/28759234-17bf937a-7571-11e7-9bbd-dfac4e7947a3.png)

**Comment by WtfJoke** [comment]
Ah, youre using the rtc2gitcli docker image. My previous comments were based on information about rtc2git (the python version)

Have a look at Usage of rtc2gitcli (the java version) and this issue for better explaination of src/dst workspace [rtc2gitcli#30](https://github.com/rtcTo/rtc2gitcli/issues/30)

If you have question feel free to ask

**Comment by julioarruda** [comment]
Ok.. I tried to used this before, but i have a problems to install this in my machine. The docker version running and decided to try this.


When i try to install the rtc2gitcli, the IBM Instalation Manager return an error about the url jazz.net, because this need authentication and the app not show options to apply this auth.

**Comment by WtfJoke** [comment]
I'm actually confused which one you tried to use before and install. 😖 

The docker image defaults to rtc2gitcli (not this project), try to ask there about setting a workspace up or see my linked issue (https://github.com/rtcTo/rtc2gitcli/issues/30). 

Only the docker image with tag "python" contains this project (rtc2git).
