### ISSUE TITLE
History is not being migrated....

### ISSUE THREAD

**Issue by vijayreddy579** [WtfJoke/rtc2git#126]
I have a Stream with two components.
When I try to migrate the components I'm not getting the history even after enabling the Provide History value true in config.ini
UseProvidedHistory = True

What I observed is: History files are not created:
History file not found: C:\\rtc2git-2.0\History\History_SDP__tNv_AG4TEeer2tKvDbbAhg.txt

Could you please help me out on this?

**Comment by WtfJoke** [comment]
Hi gvreddy

If you set UseProvidedHistory=true, you need to create those files manually, see [here in the wiki (Getting your history files) ](https://github.com/rtcTo/rtc2git/wiki/Getting-your-History-Files).

If you have no history with useprovidedhistory=false, then you might not have old baselines in that stream or dont use baselines at all. Could this be the problem in your case?

I would suggest you to follow the wiki entry to create the history files.

**Comment by vijayreddy579** [comment]
Thank you @wtfJoke ...
Could you please mention the same info in readme file if  applicable...
