### ISSUE TITLE
lcsm is not recognized as an internal or external command

### ISSUE THREAD

**Issue by ljhaywar** [WtfJoke/rtc2git#13]
I'm running migration.py, and I'm getting the following error:
'lcsm' is not recognized as an internal or external command, operable program or batch file. 

Where can I get lcsm?

**Comment by WtfJoke** [comment]
Its called "SCM Tools" and can be found under All Downloads on the RTC Product Page of your version.
In case of version 5.0.1 (which I used), you can use: https://jazz.net/downloads/rational-team-concert/releases/5.0.1?p=allDownloads

After you have downloaded it and exctrated it to a folder of your choice make sure it is runnable from every folder in your console (in windows you can set the environment-variable PATH to the folder where your lscm.bat is)

**Comment by ljhaywar** [comment]
Thanks for another fast response!

**Comment by WtfJoke** [comment]
No worries glad to help :)
