### ISSUE TITLE
Ambigous selector "repository_workspacename" matched multiple items 

### ISSUE THREAD

**Issue by ravirange7** [WtfJoke/rtc2git#135]
Hi ,
I am trying to copy my RTC repository (version 6.2) to git server . 
I have set "useExistingWorkspace=TRUE" ,and created  a repository from stream with baseline set to initial one . However when I execute migration.py script , it always throws "ambiguous selector -repository workspace name matched multiple items ". I am not sure why its showing multiple workspace , while I have only one workspace on RTC server . Can you please check and let me know if I am missing something here .

**Comment by WtfJoke** [comment]
Hi Ravirange

Thats an error displayed from the scm tools, which says you have multiple workspace for that name.
What does `scm list workspaces -n "YOUR_NAME"` have for an output?

**Comment by april2018** [comment]
I get this same issue when I set useExistingWorkspace to False. The workspace is created and then it is ambiguous. Any ideas?

**Comment by WtfJoke** [comment]
Have you checked the output of 'scm list workspaces -n "YOUR_NAME"' like I previously asked?
