### ISSUE TITLE
copying RTC snapshot to GIT 

### ISSUE THREAD

**Issue by ravirange7** [WtfJoke/rtc2git#136]
Hi ,
I want to copy  snapshot from RTC server to GIT .  I am not sure if there is anyway to copy all snapshot directly into git server using rtc2git tool .

Thanks for your help !!

**Comment by WtfJoke** [comment]
Hi

rtc2git doesnt support snapshots. [rtc2gitcli ](https://github.com/rtcTo/rtc2gitcli/) does support tags (maybe also snapshot, im not 100% sure). Im also not sure if rtc2gitcli works with rtc 6.0.2 (some user reported it did).

If you only want the data from the snapshot (without history), you can checkout the snapshot in rtc and copy all the files to your git repo and commit them.

This process you can repeat for all snapshots, which you want to copy.

**Comment by ravirange7** [comment]
Ok Thanks , that should be right way of copying snapshot.
