### ISSUE TITLE
Tool Not Working - Not Sure Why

### ISSUE THREAD

**Issue by april2018** [WtfJoke/rtc2git#138]
Hi, 

I have updated the config.ini and ran the RTC2Git tool. Straight away I get an issue 

```
   usage: git check-ref-format [--print] <refname>
   or: git check-ref-format --branch <branchname-shorthand>
```

I removed the normalize from the code during the branch check. This gets me passed this issue. My Stream name and workspace name are basic one word strings.

Then I set the useExistingWorkspace to False. The workspace creates but later on I get:

```
Ambiguous selector "GITMigrationWorkspace" matched multiple items: 
Possible matches: 
  (1010) "GITMigrationWorkspace"
  (1011) "GITMigrationWorkspace"

```
Finally I try and create a new repository workspace. I select all components but load no projects. The workspace is connected to the stream I want to migrate. I set the useExistingWorkspace to True and set the Workspace name to the newly created workspace. Then I see the following issue:

```
17:16:10 - Start (re)loading current workspace: lscm load -r <RTC Repo listed here> WorkspaceToMigrate --force
Unexpected exception
com.ibm.team.rtc.cli.infrastructure.internal.core.CLIClientException: Internal error
	at com.ibm.team.filesystem.cli.core.util.StatusHelper.toCLIClientException(StatusHelper.java:731)
	at com.ibm.team.filesystem.cli.core.AbstractSubcommand.run(AbstractSubcommand.java:53)
	at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.run(SubcommandLauncher.java:601)
	at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.doStart(SubcommandLauncher.java:370)
	at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.run(SubcommandLauncher.java:130)
	at com.ibm.team.filesystem.cli.client.internal.daemon.CommandLineClient.handleRequest(CommandLineClient.java:186)
	at com.ibm.team.filesystem.client.internal.http.ProtocolSwitchingHttpHandler.handle(ProtocolSwitchingHttpHandler.java:46)
	at com.ibm.team.filesystem.client.internal.http.HttpConnection.readNextRequest(HttpConnection.java:628)
	at com.ibm.team.filesystem.client.internal.http.HttpConnection$1.run(HttpConnection.java:470)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.lang.IllegalArgumentException

```

Please note my command line tool is set to lscm and I am going to try and switch now to scm to see if this makes a difference.

Any ideas on where I am going wrong?

Thanks!

**Comment by april2018** [comment]
I have deleted all workspaces. Now on this run the workspace is loaded "Successfully loaded items in the sandbox". The flow target updates. Then it goes into a process of "Start collecting changeentries". It cycles through each component. Then is says "Start collecting changes since baseline creation". Finally is says "Found no changes to accept".  Essentially it is finding nothing to load to GIT.

**Comment by WtfJoke** [comment]
Hi April

About found no changes to accept. Have you read the wiki page about resetting your workspace to an older state [here](https://github.com/rtcTo/rtc2git/wiki/Resetting-your-workspace-to-an-older-state)?

Probably rtc2git wasnt able to reset your workspace automatically, usually then it doesnt find any changesets to accept.

Hope that helps, let me know if it works out.

Do you know what was the source of your initial problem?

**Comment by april2018** [comment]
Thanks. I didn't try this as I was a bit confused. It says workspace but the screenshot was of the stream. The workspace should have nothing if it at the start. Should I clone my current stream and then reset it? I just want to make sure I'm not at risk of loosing code. Thanks!

**Comment by april2018** [comment]
Just to say on my original problem. I did two things removed the normalise check to get through issue 1. Then the duplicates I think was caused by a bug in the tool. I cleared all the workspaces created by the tool and removed the git local repo location. I also put some print statement or shout statements in the code to make sure the correct flags were being set.  Then finally I switched from lscm commands to scm. That has got me to where I am now.

**Comment by april2018** [comment]
Manuel, Thanks I think moving it back to the base has fixed my issue. I only set one baseline back but it seems to update other baselines. Not sure what is triggering now for it to pick up changes but I won't know if everything is there until I let it do a full cycle. Is there a way to run it without having to manually type y to accept each changeset? Thanks

**Comment by WtfJoke** [comment]
Usually you shouldnt have to type y to accept each changeset. Do you have merge problems?

**Comment by april2018** [comment]
I shouldn't have any merge issues. Maybe there is something I can set up in the config file to auto accept? Thanks

**Comment by WtfJoke** [comment]
Can you please share a screenshot or log message how it looks (how it asks you to press y).
