### ISSUE TITLE
unable to run rtc2git 

### ISSUE THREAD

**Issue by himmakam** [WtfJoke/rtc2git#140]
I am  trying to migrate an RTC repository to git using the tools.. I've set up the config.ini file & when I run the migration.py script I get the following error: Not sure where to set the configured directory in migration.py

python3.4 migration.py
refs/heads/Foundation_L10N
refs/heads/Foundation_L10N_branchpoint
Configured directory '/data/rmg/sources/apps/IBM/jazz/rtc2git-develop1' already exists, please make sure to use a non-existing directory

**Comment by WtfJoke** [comment]
In the config.ini you need to provide directory like that (the directory will be created by rtc2git):

Directory = /temp/myWorkingDirectory

**Comment by himmakam** [comment]
Thanks a lot. I added this before in Migration sections. Now I added in General section of config.ini with which it worked
