### ISSUE TITLE
where can I see the repo created

### ISSUE THREAD

**Issue by himmakam** [WtfJoke/rtc2git#141]
Hi, I used the steps and able to run the migration successfully. But I am not able to see the repo in git. 
The last output is as below. Do I need to perform more steps to see this repo created in git. Appreciate your help here. 

All changes accepted - Migration of stream 'Foundation_L10N' is completed.
You can distribute the git-repo 'testbindu6.git'.

**Comment by WtfJoke** [comment]
Its in your specified (work-)directory. There are two folders one the bare repo with .git and once the cloned repo. Push the cloned one (if you dont have access to filesystem of git server). 

Check #139 for more details (or 
https://help.github.com/articles/adding-an-existing-project-to-github-using-the-command-line/ step 8 onwards)

**Comment by himmakam** [comment]
Hi, thanks for the reply. But somehow am seeing no files in cloned repo. (with no .git folder). Am not sure if am missing something. I am attaching the log here. Appreciate your help on this.
[log.txt](https://github.com/rtcTo/rtc2git/files/1897280/log.txt)

**Comment by WtfJoke** [comment]
According to log the following is happening:

1.  Resetting to initial baseline --> good, works
2.  Found no changes to accept --> Thats not so good. For some reason no change is found. 

Can you check if there is something in branch 'Foundation_L10N' or is it empty as well?

Can you show me your config?

**Comment by himmakam** [comment]
Hi, the stream is not empyt. And I pasted the config as below here. 

[General]
Repo=https://jazzxxx.hursley.ibm.com:9443/ccm
User=<userid>
Password=**********
GIT-Reponame = testbindu6.git
WorkspaceName=rtc-git-branch
Directory = /data/rmg/sources/rtc-git-migration

[Migration]
# Stream to be migrated,  referenced by Name or UUID
StreamToMigrate = Foundation_L10N
#Directory = /data/rmg/sources/rtc-git-migration
#workDirectory = /data/rmg/sources/rtc-git-migration1
UseProvidedHistory = True

**Comment by himmakam** [comment]
Sorry for the same. It is working fine now. But I have this doubt - How can I get rid of the user input. 

git commit -m "xxxxx: As an operations admin I should be able to deploy - Documentation" --date "2015-07-23 18:09:17" --author="xxxxxx <xxxxx@in.ibm.com>"
Do you want to continue? Y for continue, any key for abort

**Comment by WtfJoke** [comment]
Which rtc version do you use?

Usually it should only ask for Y if it has problems when accepting changesets...
Did you experienced problems before?

You could set useAutomaticConflictResolution to avoid this question see here:
https://github.com/rtcTo/rtc2git/blob/develop/config.ini.sample#L38

**Comment by himmakam** [comment]
we use RTC 5.0.2. And I already had the setting AutomaticConflictResolution to True. Inspite of these, it is waiting for the user input.

**Comment by WtfJoke** [comment]
Since you dont answer my questions fully.
You can comment this line out (call of  self.is_user_aborting(changeEntry)):
https://github.com/rtcTo/rtc2git/blob/develop/rtcFunctions.py#L235

Then no questions are asked
