### ISSUE TITLE
Getting null pointer exception when it tries to create the list of baselines.

### ISSUE THREAD

**Issue by adamthompson93** [WtfJoke/rtc2git#147]
RTSSMigrate    | [2018-04-24 16:47:46] Create the list of baselines
RTSSMigrate    | [2018-04-24 16:47:47] java.lang.NullPointerException
RTSSMigrate    | 	at to.rtc.cli.migrate.MigrateTo.createTagListFromBaselines(MigrateTo.java:251)

**Comment by WtfJoke** [comment]
Hi Adam

This is an [rtc2gitcli ](https://github.com/rtcTo/rtc2gitcli/issues)issue. Please create it there
