### ISSUE TITLE
getting Ambigous selector for one of the RTC stream 

### ISSUE THREAD

**Issue by ravirange7** [WtfJoke/rtc2git#148]
Hi ,
I am getting ambiguous selector for one the RTC stream . Can you please let me know what all places I have to modify if I want to pass uuid and not name .  And what will be the command line. .Thanks for all your help  !!

**Comment by WtfJoke** [comment]
You dont need to modify any code. Simply set in your config StreamToMigrate=MYSTREAMUUID as described here
https://github.com/rtcTo/rtc2git/blob/develop/config.ini.minimum.sample#L11

**Comment by ravirange7** [comment]
Ok , Thanks a lot for your help !
