### ISSUE TITLE
Unable to migrate

### ISSUE THREAD

**Issue by OnacProudmoore** [WtfJoke/rtc2git#158]
Hi!

I have been trying to use this tool, but I couldn't migrate the code history to Git.
Among others I have got the message "Found no changes to accept"

After this I tried reverting my baseline to one that's several years old, but I couldn't spot any difference between the outputs I got.

Here is my config.ini and my output from Python. I hope you will be able to tell me what I am doing wrong.

**config.ini**
[General]
Repo=https://igartc03.swg.usma.ibm.com/jazz/
User=user
Password=pass
GIT-Reponame = testRepo.git
WorkspaceName= Duplicate_Stream_for_Migration
Directory = \temp\myWorkingDirectory
useExistingWorkspace=True

[Migration]
StreamToMigrate = _jCjpwGGgEeODDeXuDiuUmg

**Python output**
refs/heads/_jCjpwGGgEeODDeXuDiuUmg
refs/heads/_jCjpwGGgEeODDeXuDiuUmg_branchpoint
13:17:10 - Found existing git repo in work directory, resuming migration...
13:17:16 - Login failed. Trying again without quotes.
Logged in to https://igartc03.swg.usma.ibm.com/jazz/
13:17:22 - Get UUID of configured stream _jCjpwGGgEeODDeXuDiuUmg
13:17:25 - Set core.ignorecase to false
Switched to branch '_jCjpwGGgEeODDeXuDiuUmg'
13:17:26 - Start (re)loading current workspace: lscm load -r https://igartc03.swg.usma.ibm.com/jazz/ Duplicate_Stream_for_Migration --force
Problem running 'load':
Unmatched workspace "Duplicate_Stream_for_Migration"
13:17:26 - Load of workspace finished
13:17:27 - Set new Flowtargets
The flow targets were added.
Problem running 'set flowtarget':
The specified value for the --current option is not valid. Try 'lscm help set flowtarget' for more information.
13:17:32 - Warning - UseProvidedHistory is set to false, merge-conflicts are more likely to happen. 
 For more information see https://github.com/rtcTo/rtc2git/wiki/Getting-your-History-Files
13:17:32 - Start collecting changeentries
Already on '_jCjpwGGgEeODDeXuDiuUmg'
13:17:32 - Start collecting changes since baseline creation
Problem running 'compare':
Unmatched workspace "Duplicate_Stream_for_Migration"
13:17:33 - Found no changes to accept
Successfully logged out of https://igartc03.swg.usma.ibm.com/jazz/
13:17:33 - 
All changes accepted - Migration of stream '_jCjpwGGgEeODDeXuDiuUmg' is completed.
You can distribute the git-repo 'testRepo.git'.

Process finished with exit code 0

**Comment by WtfJoke** [comment]
Hi there
When you look closely at the logs you can see a message that your workspace doesnt exist. Please make sure that it exists
