### ISSUE TITLE
Git Case Sensitive Files. 

### ISSUE THREAD

**Issue by diomedesantonio** [WtfJoke/rtc2git#161]
When migrating the changesets from RTC to Git the following error message shows up:

There was a [FAILURE](Update failed
There were issues encountered during the updating of the sandbox.
Unable to modify /Project/NT/TEST.ini because its not a file.  Reload component Project
Check the log for details about the error at "C:\Users\Diome\AppData\Local\jazz-scm". If you have configured custom logging check your log configuration settings for the path to the log file.).

C:\Users\Diome\AppData\Local\jazz-scm\log:
<message>com.ibm.team.filesystem.client.FileSystemStatusException: Status ERROR: com.ibm.team.filesystem.client code=0 There were issues encountered during the updating of the sandbox. null children=[Status ERROR: com.ibm.team.filesystem.client code=0 Unable to modify /Project/NT/TEST.ini because its not a file.  Reload component NetMAC_Project com.ibm.team.filesystem.client.FileSystemException: Unable to modify /Project/TEST.ini because its not a file.  Reload component Project]</message>

The file cannot be found because there was a change set in RTC where the original file (test.ini) was replaced with a new file TEST.ini. Instead of deleting and creating a new file, RTC considered the change as renaming as shown below:

[2020-10-21 17:13:37]           Changes:
[2020-10-21 17:13:37]             --mc- \Project\TEST.ini (Renamed from \Project\test.ini)

Is there a way to disable case sensitivity and threat it as the same file during the migration? 

Thanks

**Comment by WtfJoke** [comment]
Hi @diomedesantonio 

Its possible, but not on Windows. Thats the main reason why we advice to do the migration on linux. 👍

**Comment by WtfJoke** [comment]
I'll close the issue for now. If you have any problems doing the migration on linux, let me know by a comment.
