### ISSUE TITLE
I am having trouble with configuration file.

### ISSUE THREAD

**Issue by Qusai3toon** [WtfJoke/rtc2git#163]
I tried to add my information in the **configuration file** but I am not sure what information I should put in the config file.

**Can anyone help me with this?**

This is my config file :

`[General]
Repo=https:https://github.com/Qusai3toon/repositoryForRTCMigration.git
User=Qusai3toon
Password=myPAssword
GIT-Reponame = repositoryForRTCMigration.git
WorkspaceName=C:\Users\QusaiAtoon\workspace
Directory = C:\Users\QusaiAtoon\MigrateHere
useExistingWorkspace = true

[Migration]
StreamToMigrate = Application A`

**Comment by Qusai3toon** [comment]
I really hope that someone @WtfJoke  help me, I still have a problem with the configuration file and this the output when I execute the (migration.py) and here is the output : 


refs/heads/ApplicationA
refs/heads/ApplicationA_branchpoint
10:24:26 - Migration will take place in C:\Users\QusaiAtoon\MigrateHere
Initialized empty Git repository in C:/Users/QusaiAtoon/MigrateHere/repositoryForRTCMigration.git/
10:24:26 - Repository was created in C:\Users\QusaiAtoon\MigrateHere
Cloning into 'repositoryForRTCMigration'...
warning: You appear to have cloned an empty repository.
done.
10:24:26 - Set core.ignorecase to false
'lscm' is not recognized as an internal or external command,
operable program or batch file.
10:24:26 - Login failed. Trying again without quotes.
'lscm' is not recognized as an internal or external command,
operable program or batch file.
Login failed. Please check your connection and credentials.


Thanks in advance. ♥

**Comment by WtfJoke** [comment]
Keep an eye on the information in the log: "'lscm' is not recognized as an internal or external command". 

You need to make sure lscm/scm (from in the readme mentioned scm tools) is on your path.

That will probably help

**Comment by Qusai3toon** [comment]
@WtfJoke  thank you, that was helpful and the migration started working. 
but now what I see is that **it creates two folders and none of them contains the files and folders that are in my stream. but one of them has a branch with the name of my stream.**
Can you tell me where can I find the files that I'm looking for. 
Or what am I doing wrong.
And again thanks for the help ♥. 

**UPDATE**

I read the other ISSUES and I understood what were my problems, but now what I see the files that are in my initial baseline, not the final (last) baseline. 

again thanks in advance for the help. ♥

**Comment by Qusai3toon** [comment]
The problem was that my baselines were not in the right order so I provided the history and every thing worked well, Thanks for the help and what a great tool.
