### ISSUE TITLE
Switch branch aborted

### ISSUE THREAD

**Issue by ljhaywar** [WtfJoke/rtc2git#17]
After completing one stream, the script attempted to switch branches, but the following was displayed:
![aborted](https://cloud.githubusercontent.com/assets/3940962/7631294/061ac68e-fa0e-11e4-8761-0f0217b41c0e.png)
However, the script continued on with the lscm commands.  Does this mean that the changes the script is accepting and committing are actually being committed into the previous branch?  

Also, any ideas on what caused this problem and how to avoid it?

**Comment by ljhaywar** [comment]
It looks like I can add a command to stash the changes before running the checkout command, so I'll try that.  My concern is why I have these loose changes that haven't been committed.

**Comment by WtfJoke** [comment]
>Does this mean that the changes the script is accepting and committing are actually being committed into the previous branch?

Yes

>My concern is why I have these loose changes that haven't been committed.
I dont know, how this can happen. After every change git add -A and git commit will be executed, so there shouldnt be any left changes.

**Comment by WtfJoke** [comment]
Can you reproduce the behavior? I tried reproducing this, by modifying some files in the rtc2git repository and I'm not able to reproduce it (I changed some files and used git checkout -b "somebranch" / git checkout "someotherbranch").

My idea to solve the problem was, to check for the return code of the checkout commands and throw an error if something goes wrong. But I like to test it somehow to verify it will solve the problem.

**Comment by ljhaywar** [comment]
Unfortunately, I don't remember which loose files prevented the branch switch.  They were likely c files.

I'm currently running the script with the added command to stash changes before switching branches.  Once the script finishes, I'm hoping to be able to view any stashed changes (though I haven't googled how to do that yet).  

Running the script on my streams takes many, many hours (haven't made it through successfully yet).  Once I get things working, I might be able to try again without the stash command to see if it's reproducible.  Are you an IBMer?  If so, I might be able to get you access to the code.

**Comment by WtfJoke** [comment]
> I'm hoping to be able to view any stashed changes (though I haven't googled how to do that yet).

You can simply type "git status" in your cmd and you get a nice overview. :+1: 



> Running the script on my streams takes many, many hours (haven't made it through successfully yet). Once I get things working, I might be able to try again without the stash command to see if it's reproducible. .

Yes it takes really long, I experienced that too (accept command consumes a lot of time). As a workaround you could just migrate one stream at a time. So the programm will finish when one stream is migrated, then you can verify if everything is allright (by using git status) and if necessary stash them by using git commit and push the changes.

>Are you an IBMer? If so, I might be able to get you access to the code

No, I am not an IBMer. Yeah would have been nice to had a look on it. :smiley: I might try to investigate the circumstances a bit more. Im pretty sure other people experienced this problem as well.

**Comment by WtfJoke** [comment]
Since I removed support of multiple streams for the moment, this wont be a critical issue anymore. If you can reproduce the behaviour somehow, I would happy to know the circumstances anyways to fix it :smiley:
