### ISSUE TITLE
"Press any other key to skip this changeset and continue" does not continue

### ISSUE THREAD

**Issue by ljhaywar** [WtfJoke/rtc2git#18]
Occasionally, the script will report, "Press Enter to try to accept it with next changeset together, press any other key to skip this changeset and continue."  When I press any other key, nothing happens.  I have reproduced this several times.  I have to stop the script and restart it.  

I'm using Windows 7 and running the script in Command Prompt.

**Comment by WtfJoke** [comment]
I will have a look on it during the next days... 

Im not sure about it, but can you check if you press another key **and** afterwards Enter if it works in that case?

The text in that case might be misleading then. I think its just how the python input works, you need to press enter to finish your input.

**Comment by WtfJoke** [comment]
> Im not sure about it, but can you check if you press another key and afterwards Enter if it works in that case?

I just verified that. It is like that, please check it and if it doesnt work reopen the issue. Thanks :)

**Comment by WtfJoke** [comment]
I experienced this today too... Need to recheck it.

**Comment by WtfJoke** [comment]
I changed the message to answer y(es) or n(o). If there is another input, the question gets asked again. I tested it and couldnt reproduce the behaviour anymore.
