### ISSUE TITLE
Resuming script starts the script at the beginning

### ISSUE THREAD

**Issue by ljhaywar** [WtfJoke/rtc2git#19]
My script had been running for quite a while and had successfully created 3 git branches to match 3 of my 5 streams.  As I was watching the script's output, I saw it try to get the list of changeentries, and it choked with an out of bounds type exception on splittledlines[somenumber].  (I didn't get a screenshot with the details).  I restarted the script, and I noticed that it checked out the first branch in the stream list (not the branch it had been working on) and listed that it was getting 286 changes.  I opened the workspace in RTC and confirmed that it was accepting changes in the very first stream listed in config.ini.  It's as if the script did not resume where it had left off and instead started from the beginning.

The script then got stuck on a merge conflict, so I stopped it, resolved the conflict in RTC, and restarted the script.  This time I saw something about getting changes 1/274.  It's like the script resumed where it had left off in this case.

In what cases does the script start from the beginning and in what cases does the script resume where it left off?

**Comment by ljhaywar** [comment]
The script has been running for the last several hours.  It choked again on splitted lines, and I took a screenshot this time.  I had modified the script to set the Date to None if it couldn't find it:
                    splittedlines = cleanedline.split(informationseparator)
                    revisionwithbrackets = splittedlines[0].strip()
                    revision = revisionwithbrackets[1:-1]
                    author = splittedlines[1].strip()
                    email = splittedlines[2].strip()
                    comment = splittedlines[3].strip()
                    if len(splittedlines) > 4:
                        date = splittedlines[4].strip()
                        shouter.shout("date: " + date)
                    else:
                        shouter.shout("********DATE NOT FOUND - SETTING TO NONE*******")
                        date = None
                    changeentries.append(ChangeEntry(revision, author, email, date, comment))

So the output looked like the following the the line "********DATE NOT FOUND - SETTING TO NONE*******" printed just above the screenshot:
![splittedlines](https://cloud.githubusercontent.com/assets/3940962/7686352/2e0644e0-fd63-11e4-8490-d883f0847138.PNG)

Then I restarted the script, and I saw the same thing I did earlier today where the script began loading changes from the first stream in config.ini, which was already completed:
![loadfirststream_whiteout](https://cloud.githubusercontent.com/assets/3940962/7686458/e1143c68-fd63-11e4-8696-9cd39c766567.png)

I then saw a mention in the script's output about loading 286 changes.  Any ideas on what I can do to prevent the script from starting over?  I'm not sure how to finish the migration if the script chokes and starts over halfway through.

**Comment by ljhaywar** [comment]
I just opened the branch's history, and it looks like it has gone through the stream's history 3 times and is currently going through it a fourth time. (I must not have noticed it the first time it happened.)

**Comment by ljhaywar** [comment]
I just noticed that the git repo's history only dates back about a year despite the history in RTC going back several years.  I've confirmed the history file has over 6000 lines, with the lines at the end of the file pointing to the correct old changesets that are not appearing in the git repo.  The script keeps listing 286 as the number of changesets in the stream.  Still investigating...

**Comment by WtfJoke** [comment]
> In what cases does the script start from the beginning and in what cases does the script resume where it left off?

The script is currently not that intelligent, at the moment it doesnt remember the last stream where it worked.. As long you are migrating the same stream it will resume where it left off. But after you migrated a complete stream, you should adjust your config and remove the migrated stream of the "StreamsToMigrate" list before you resume the script.

It simply goes over each stream, so if you dont remove it after you have fully migrated it, it doesnt know that its already migrated...

**Comment by WtfJoke** [comment]
> I've confirmed the history file has over 6000 lines, with the lines at the end of the file pointing to the correct old changesets that are not appearing in the git repo. The script keeps listing 286 as the number of changesets in the stream. Still investigating...

The reason is probably that these old changesets are created before the current baseline of your stream and thus already part of your workspace on your initial load.
To get all changes you need to set InitialBaseLine in the config to the earliest Baseline of your stream.

You can find the names of the baselines by using following command:
lscm --show-uuid y list baselines --components YOURCOMPONENT -r REPOURL --max 20000

**Comment by ljhaywar** [comment]
The earliest baseline of my code is from 2013 despite my having history from several years prior (the code was originally in another source control system and migrated to RTC).  So you're saying that I won't be able to convert history prior to my first baseline?  Is this a scm limitation or a script limitation?  (If it's a script limitation, I'm wondering if I could modify it to make it work.)

I'm fairly certain the script was choking when trying to view the change entries as part of getting ready to migrate a new stream.  This makes sense with what you wrote above--if the script is in the middle of stream, it will resume there.  If it is between streams, it will start at the beginning.  It sounds like I could migrate one stream at a time, and it would work--is that right?

**Comment by WtfJoke** [comment]
> So you're saying that I won't be able to convert history prior to my first baseline? Is this a scm limitation or a script limitation? (If it's a script limitation, I'm wondering if I could modify it to make it work.)

Im not sure wheter its a scm or script limitation. What im sure is, its a limitation from the scm compare command. If you cant create a workspace, which is that old, you cannot compare it (with lscm compare) with newer baselines/streams.

I have a similar situation our code goes back about 15 Years and it was migrated from CVS. My idea was here to migrate the cvs history (again) to git (I made some test using http://cvs2svn.tigris.org/) and then start the migration from rtc to git (maybe on top of it, if possible or maybe its possible to merge 2 git repo together to one)





> if the script is in the middle of stream, it will resume there. If it is between streams, it will start at the beginning.

Yes, thats correct.



> It sounds like I could migrate one stream at a time, and it would work--is that right?

Yes, just put only one stream at a time in your config in the StreamsToMigrate Part

**Comment by ljhaywar** [comment]
I'll poke around and see if anything jumps out at me as to how to convert older history.

Were you successful in migrating your cvs history and then migrating your rtc history on top of it?  If so, did you have multiple branches?

**Comment by WtfJoke** [comment]
> I'll poke around and see if anything jumps out at me as to how to convert older history.

Thanks, I look forward to that :+1: 



> Were you successful in migrating your cvs history and then migrating your rtc history on top of it? If so, did you have multiple branches?

So far I didnt tried the on top of it part. I only tried to migrate the rtc history and the cvs history separately and this worked as far as I could tell. 

If you ask me if our cvs had multiple branches, yes it had that. I didnt checked if the migrated git repo have the same branches (but I think they do, since cvs2svn looks really advanced/complicated with all the settings :stuck_out_tongue_closed_eyes: )

Our company hasnt decided yet, if we switch to git. During the next months we decide that...

**Comment by ljhaywar** [comment]
Not sure why, but when I discard changes from the original CVS import, they aren't being listed in the Incoming changes view.  However, when I suspend changes from the original CVS import, they are being listed in the Suspended changes view.  I'm going to see if I can modify the script to resume changes instead of accepting them.  More details are posted in https://jazz.net/forum/questions/184986/how-can-i-revert-repository-workspace-back-in-time

**Comment by WtfJoke** [comment]
It seems the cvs history imported data differs from the usual created changeset.

Did I get you right, you want to prepare a workspace where you suspend your whole cvs history? :o
Afterwards resume them one by one?

I'll follow the link anyways and interested what solutions might come up. Thanks for the update/link.


As for this origin issue. Most likely the behaviour now works as designed. But I need to confess its not obvious from where it resumes and when you need to adjust config before you resume.

**Comment by ljhaywar** [comment]
Yes, I'm planning to prepare a workspace where I suspend the cvs history and resume it one by one.  Can you think of a reason why this wouldn't work? (Or maybe isn't possible?)

**Comment by WtfJoke** [comment]
Well im not sure what your experience is with suspending changesets.... But we suffered a lot with performance issues and sockettimeoutexceptions while doing that. If I imagine you want to do that. :scream:

In case you do that one by for example with another script it is probably possible (at least you can give it a try), but the question is how long you will have to wait until every changeset is suspended (assuming you have history of a couple of years). And the other thing will be, if you have everything suspended, you need to resume it one by one and this takes probably the same amount of time a second time. So I imagine that the migration then will take very very long (mabye even weeks). 

But keep me updated about your tests. I might be wrong with the duration. :moyai:

Another question: Is there some reason why you dont try to migrate the cvs part to git using tools like cvs2svn? (CVS-Server not available anymore or you just dont want to migrate them again, cause they were already migrated to rtc once?)

**Comment by ljhaywar** [comment]
I was able to suspend all of the changesets for one of our streams in less than a minute using the Eclipse client.  (I figured I'd try it manually before working on scripting it.)

"if you have everything suspended, you need to resume it one by one and this takes probably the same amount of time a second time"  I'm curious why this would be different from accepting changesets one by one?

"Is there some reason why you dont try to migrate the cvs part to git using tools like cvs2svn?"  I thought I'd try converting all of the history using Resume before playing with another conversion tool.  My hunch was that trying to get the branches to line up perfectly for both a CVS migration and a RTC migration would be challenging.

**Comment by WtfJoke** [comment]
Wow :D Awesome, I am surprised it was so fast. 

> I'm curious why this would be different from accepting changesets one by one?

I think it isnt any different. Its just the part, which takes the most amount of time during the migration (the accept of a changeset).

> My hunch was that trying to get the branches to line up perfectly for both a CVS migration and a RTC migration would be challenging.

Ok, yeah well it makes sense. I was just curious. Keep me on track.

**Comment by ljhaywar** [comment]
Will do :)

**Comment by ljhaywar** [comment]
Good news!  I got a small piece to work.  I created a repository workspace manually in Eclipse, Suspended all of the Changesets, and modified the Accept command to be a Resume.  I successfully got the first 17 changesets from the original CVS repo into a git repository (I ran with a small subset as a first test).

Things got a little dicey when I tried to run with more than one stream, probably because the compares were off (I'll poke more into this now that I know the basic idea will work).  If I stick with running one stream at a time and pull in the changesets by using a Resume, do I need to set the oldest stream or the baseline in the config file?  Are those settings being used in any way besides getting the workspace to the right point in time?

**Comment by WtfJoke** [comment]
Nice job!



> do I need to set the oldest stream or the baseline in the config file?

No

Another question to before... How did you suspend all changesets?

**Comment by ljhaywar** [comment]
To suspend all changesets:
1.  In the Pending Changes view, right-click your component and select Show > History
2.  In the history view, select all of your changes except for the very first change
3.  Right click and select Suspend

**Comment by ljhaywar** [comment]
Finally finished migrating all of my history for one stream and am working on migrating a second.  Unfortunately, the shared history at the beginning of the streams is not showing up as shared as they have different commit hashes.  Were you able to maintain shared stream history when you migrated to Git?

**Comment by WtfJoke** [comment]
Congratulations :tada:  

I dont know what you mean by shared history? :confounded: Can you please give me an explaination.

**Comment by ljhaywar** [comment]
Thanks! I love your use of emoticons!

Some of my streams were branched off of each other, so their history has the same changesets.  I'd like to retain that shared history as branches in the same git repo.

**Comment by WtfJoke** [comment]
Haha thanks :blush:

So you mean for example you had a headstream and releasestreams and the history before the releasestream got created is the same?

And although the the same changes they are git-wise different commits, cause they got recreated?
And you want them to be the same commits?

If that's what you want I'm not sure if that's somehow possible. But is there a specific reason why you want to do that?

As long as every branches is fine on each one, its ok I guess?

In an earlier version of the program it worked like this way. I branched off after all changes of the streams baseline has been accepted. In the end I looped over all streams again and updated them to each head version.

But for some reason I changed this part of the program....

**Comment by ljhaywar** [comment]
Yes, exactly!

It's probably not a huge issue if the commits are duplicate, but ideally I'd like to mirror what we have in RTC.  I've been talking with a git expert, and he walked me through how to do a "git rebase --onto" in order to merge the history together.  This will also make the migrations shorter if I don't have to migrate a bunch of duplicate changsets.  The trick will be to migrate in the right order to maintain the branch structure.

**Comment by WtfJoke** [comment]
Yeah, I used to have it like that you described. However take care, when you do the split or what you rebase on what.. Because usually when we branch off a stream in our release the branched off stream continues independently from the head/mainstream.

Would be cool, if you can tell me in the end what you did and what were the results out of it

**Comment by ljhaywar** [comment]
I'm running tests now.  I'll let you know if this works out for us.

**Comment by WtfJoke** [comment]
About your initial request/problem. I've decided to remove the option to migrate multiple streams to avoid confusion.... In future it might make sense to reimplement it and persist the current progress somehow.

**Comment by ljhaywar** [comment]
I've run some tests and rebasing is working for us, so we don't have to migrate duplicate history. Two big advantages:  the migration is significantly faster since you're only migrating the common history once and the Git history reflects what actually happened in RTC.

In this example, stream A's history was joined to stream B's:
git fetch origin
foo is commit in B that both branches have (even though the hashes don't match)
bar is commit in A that both branches have
git rebase --onto foo bar
git push --force gitlab ALocalBranchName:ARemoteBranchName

Have you implemented the change so only one stream is migrated at a time?

**Comment by WtfJoke** [comment]
Thanks for sharing. That sounds really promising. I might ask you some details again, once in the near future when we make some bigger tests with our migration. 

> Have you implemented the change so only one stream is migrated at a time?

I implemented it in branch https://github.com/WtfJoke/rtc2git/compare/develop...determinationofbaseline. I think im going to merge it today into my develop branch. I had some issues with encoding, which I wanted to find a solution approach first.

**Comment by WtfJoke** [comment]
> Have you implemented the change so only one stream is migrated at a time?

Its implemented/merged now :)

**Comment by WtfJoke** [comment]
There is one question, which popped up in my mind. How you know which history is common?

I was thinking about an example. Having release 1 (gives a release 1 stream) while start to implement release 2 (head-dev-stream) --> History is the same. 

Now the customer wants an emergency bugfix for release 1 which you deliver there, you implement it different in your head-dev-stream.

So the history is only the same to a certain point. Did you considered that or how did you do it?

**Comment by ljhaywar** [comment]
Yes, the history will only be the same up to the branching point.  After that, if someone delivered the same changeset to more than one stream, it will be duplicated as different commits.

**Comment by WtfJoke** [comment]
Yes, thats right. But how you know where the branching point was? (Usually it should be at the point where the baseline was created, but you suspended/resuming all changeset including the one which got delivered after the baselinecreation)

Do you know what I mean? Or am I just to confused to get your explaination :question:

**Comment by ljhaywar** [comment]
I think I know what you mean.  Below are the instructions I wrote.  Let me know if that doesn't answer your question.

Run the migration for each stream individually.  Before running the script for a particular stream, create a new repository workspace for that stream (do this for each run and not earlier as the suspended changes are associated with your account and not the repository workspace -- could cause conflicts if you try to do multiple suspensions).
First, get the history for the steam by following the instructions at https://github.com/WtfJoke/rtc2git/wiki/Getting-your-History-Files
Second, suspend all changes in the repository workspace:
1.  In the Pending Changes view, right-click your component and select Show > History
2.  In the history view, select all of your changes except for the very first change that is listed at the bottom of the History view. Optionally, to save migration time just select the changes that happen at and after the branching point of an already migrated stream.  To identify the branch point in Eclipse:
A. Open the Team Artifacts view
B. Expand your project area > Source Control > Stream you're migrating
C. Right-click the component in the stream you're migrating
D. Select Compare With > Another Repository Workspace or Stream...
E. Search for and select the other stream
F.  Click OK
G.  In the Change Explorer view, expand the directory labeled "Only in nameOfTheStreamYouAreMigrating"
H.  Scroll to the bottom of the list
I.  Right-click the bottom-most item in the list and select Locate Change Sets...
J.  Note the selected entry's (or entries') work item, comment, date, and time.  This entry represents the first entry that happened after the branch.
K. Next, confirm you have the correct branch point by going back to the history view and locating the changeset you identified in step J.
L.  Right-click the changeset that was delivered immediately prior to the changeset you idenItified in step J and select Locate Change Sets...
M.  In the Search Targets section, click Add Stream... and add the stream you are migrating.  Then click Add Stream... again to add the stream you are comparing against.  Verify the changeset results show that both streams have the changeset.  This is your branch point.  Store the comment, creator, and date for this changeset as you will use this later when running the rebase command.
N.  To give yourself a bit of leeway when running the migration, we'll migrate some extra changesets.  Select a changeset about 5 down from the branching point through the topmost changeset.
3.  Right click and select Suspend

**Comment by WtfJoke** [comment]
Wow! :sparkles: Thank you for your detailed explaination! 
I think I know now how you did it and what you meant :ok_hand: :penguin:

**Comment by ljhaywar** [comment]
You're welcome!
