### ISSUE TITLE
Ability to accept multiple (more than two) change sets together to avoid conflicts

### ISSUE THREAD

**Issue by jacobilsoe** [WtfJoke/rtc2git#27]
When migrating I experience that the script gives up on conflicting change sets if there is a need to accept more than two together.
If there is one change set followed by a "merge" change set everything works fine. But in the code base I am working on sometimes accepting e.g. five change sets together is required to avoid conflicts. I propose retryacceptincludingnextchangeset be made into a loop instead of just trying the next change set. This way it would continue discarding/accepting until it succeeds (or the author differs/comment does not contain the word merge).
Also to support unattended migrations adding an option to automatically attempt multiple accepts would be nice.

**Comment by WtfJoke** [comment]
Thats a good idea. I experienced this sometimes also on my repo.  What im a bit worried is, what if its never suceeds? Probably the best behaviour would be discarding them again....

**Comment by jacobilsoe** [comment]
Well, I think it must succeed at some point because you are accepting the change sets in the correct order.

**Comment by WtfJoke** [comment]
Yeah, youre probably right. Maybe even the users who accept them in a wrong order, might not run into any problems

**Comment by jacobilsoe** [comment]
Is this something you have time to work on, or should I give it a go? And what do you think about adding an "automatic conflict resolution" option?

**Comment by WtfJoke** [comment]
I wont have time so much so I would be more as happy if you can give it a go :+1: :smile:

**Comment by WtfJoke** [comment]
@jacobilsoe Did you start implementing it? I think if I find some spare during the next days/weeks, I would start implementing it.

**Comment by WtfJoke** [comment]
I implemented it, you can check it out, how it works and give feedback if necessary. :)

**Comment by jacobilsoe** [comment]
Sounds great! I'll test it when I get some spare time. :-)
