### ISSUE TITLE
Add configuration to choose between lscm and scm

### ISSUE THREAD

**Issue by jacobilsoe** [WtfJoke/rtc2git#28]
I often experience that lscm hangs whereas scm always works. It would be nice to add a configuration value for this.

**Comment by WtfJoke** [comment]
Strange... I heard from another user something similar. He changed to scm and later to fec (whatever this is :question:, an .exe, which comes with the scm tools as well). But an option, to choose from these 2 (maybe these 3), would be fine.

**Comment by jacobilsoe** [comment]
I'll implement this then.

**Comment by jacobilsoe** [comment]
Fixed as part of pull request #26

**Comment by WtfJoke** [comment]
Can you please split these stuff and create separate pull requests? I would like to review these two things separately (since my colleague will have a look on the encoding pull request).

**Comment by jacobilsoe** [comment]
Well, I can, I just didn't want to create extra branches for this as all the changes are quite simple. But if you really need it I can.

**Comment by jacobilsoe** [comment]
I would rather not have to rebase so maybe this time you can review the commit together. In the future I will make separate branches for each one.

**Comment by WtfJoke** [comment]
Ok, no worries. I'll review these together. :)

**Comment by WtfJoke** [comment]
Solved with merge of d3a17fd4c4e0e92b591ebcd503a74a1f8eeb69e1
