### ISSUE TITLE
License for rtc2git

### ISSUE THREAD

**Issue by mdoersam** [WtfJoke/rtc2git#3]
Hi there,
right now we are also trying to migrate our RTC Content to GIT.

Any plans for a license? We would like to use und extend your software for our one-time migration (contributing our changes back to you)

Cheers

Michael

**Comment by WtfJoke** [comment]
Hi Michael,

Until today I didnt thought about licenses. I'll think about it and decide during the next days under which license I am going to put it.

Glad that my programm is going to support you on your migration. :smile: 

PS: If I would decide based on my username I would choose [WTFPL] (http://www.wtfpl.net/about/)

Regards
Manuel

**Comment by WtfJoke** [comment]
I've decided for the MIT-License. Thank you in advance for any future contributions :thumbsup:
