### ISSUE TITLE
Make encoding configurable

### ISSUE THREAD

**Issue by WtfJoke** [WtfJoke/rtc2git#30]
The encoding should be configurable. If nothing is configured, the default encoding should be used (encoding = None).

This issue is resolved when the encoding is configurable in the config and a wiki-entry has been made about how to configure the encoding properly with the magic.properties

See discussion https://github.com/WtfJoke/rtc2git/pull/26#issuecomment-109801240

**Comment by WtfJoke** [comment]
Wiki-Entry can be found here: https://github.com/WtfJoke/rtc2git/wiki/Encoding

**Comment by Cloud-Forge** [comment]
Hi,

in shell.py line 23 :
`output = outputasbytestring.decode(sys.stdout.encoding).splitlines(`)
throw an error of the type :

> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 224: inval d continuation byte

even though the encoding in the config.in file is not set as utf-8. 

To circumvent the issue I had to add :
`    sys.stdout.reconfigure(encoding=generalsection.get('encoding'))`
in configuration.py line 38, so the sys encoding is set properly.
